# Site settings
title: SCH Hanoi
email: d.bui@schhanoi.com
description: SCH Hanoi description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://schhanoi.com" # the base hostname & protocol for your site
#twitter_username: schhanoi 
github_username: vietduc1441 
#google_play: 'GDGX'
#google_plus_com: '109485346959707049693'  # Community link
#google_plus_per: '+GDGManagua'  #Personal link
#facebook_app_id: 12345

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: How we work
    link: www.capegroep.nl
  option2:
    name: Customer
    link: www.facebook.com
  option3:
    name: Blog
    link: www.google.com
  option4:
    name: Contact us
    link: www.ms.com

disqus: false 
disqus_shortname: 'gdgmanagua'
# Build settings
markdown: kramdown
